name: Executando os testes no Device Farm Robin do Maestro

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Set Environment Variables
        run: |
          echo "MAESTRO_API_KEY=${{ secrets.MAESTRO_API_KEY }}" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV

      - name: Run Maestro Tests
        run: |
          maestro cloud --apiKey $MAESTRO_API_KEY --project-id $PROJECT_ID qafood.apk .maestro/